### ISSUE TITLE
Log Level

### ISSUE THREAD

**Issue by uipoet** [mixu/gluejs#10]
I've got Glue.js building a package on every view when the environment is development. Functionally, everything works great. The usability isn't so hot, however, since the console spews out dozens of logging lines on every view served.

Requesting a log level option when using the JavaScript API to hide logging, except for errors.

**Comment by uipoet** [comment]
Found `--silent` command line option.

`Glue.set('silent', true)` makes sense to me.

**Comment by ngryman** [comment]
:+1:

**Comment by fabien** [comment]
+1 - please add Glue.set('silent', true)

**Comment by mixu** [comment]
Added in bbfc8c3b, published on npm as version 0.2.2. Thanks for reporting this! BTW have a look at gluejs2 at  https://github.com/mixu/gluejs/tree/glue2 which adds a bunch of features (and will get even more stuff).

**Comment by uipoet** [comment]
Thanks @mixu! I look forward to the new features ahead.
