### ISSUE TITLE
incorrect RegExp

### ISSUE THREAD

**Issue by athibaud** [mixu/gluejs#3]
the global handler uses the expression:

``` javascript
new RegExp('.*\.js$')
```

but you use a single-quoted string and you forgot to escape the backslash so it evaluates to:

``` javascript
/.*.js$/
```

which obviously doesn't do the same thing!

**Comment by athibaud** [comment]
found about that one when trying to define custom handlers for .ejs files, there would be two handlers for those files for the both finish with 'js'!
cool project btw!

**Comment by mixu** [comment]
:+1: thanks @athibaud!
