### ISSUE TITLE
Don't assume environment variables exist

### ISSUE THREAD

**Issue by uipoet** [mixu/gluejs#31]
Our deployments started failing after upgrading from version 2.0.

Turns out this was because our environment did not define HOME during deployment.

https://github.com/mixu/gluejs/blob/93e3fad8dceb4b331851879bff0cb286891ba17a/index.js#L8

Probably best to use a more reliable path in Linux for the default.

**Comment by srquinn21** [comment]
This environment variable is only intended as a sane default for the `cache-path`. You can override this variable via the command line:

```
$ gluejs --cache-path /home/jibsales
```

Or you can do it programmatically:

```
var glue = require('gluejs');
glue.set('cache-path', '/home/jibsales');
```

**Comment by uipoet** [comment]
Tried that. The way the code is written, if HOME doesn't exist, path.normalize method fails that the object doesn't exist. This happened even when we tried disabling cache or manually defining cache-path. We use Glue.js programmatically.

**Comment by srquinn21** [comment]
Ahhhh – yes, I see now. Quick fix in the code would be:

``` javascript
var homePath = process.env[(process.platform == 'win32') ? 'USERPROFILE' : 'HOME'];
homePath = path.normalize(homePath);

...

  this.options = {
    replaced: {},
    remap: {},
    cache: true,
    'cache-path': homePath + path.sep + '.gluejs-cache' + path.sep
  };
```

**Comment by mixu** [comment]
awesome @JibSales, thanks for looking into this. I'll merge this now and test / release it tomorrow.

**Comment by uipoet** [comment]
Thanks for the speedy responses. We are excited to gain the performance bump of late as we continue rolling with Glue.js in production.
