### ISSUE TITLE
"detective": "~2.4.0" Cannot Install

### ISSUE THREAD

**Issue by danielmhanover** [mixu/gluejs#37]
Looks detective@2.4.0 contains an invalid dependency on 'esprima-six', a package which does not exist. Therefore, `npm install`fails when gluejs 2.3.9 is listed as a dependency. Would bumping detective to latest (4.3.1) break anything?

**Comment by gabel** [comment]
This affects also current version like 2.3.9 -- i'll evaluate the new version of detective (4.3.1). The broken dependency to `esprima-six` is fixed in detective >= 3.0.0

**Comment by gabel** [comment]
It works for me with `esprima-six` 4.3.1 - could you fix the dependency?
