### ISSUE TITLE
Doesn't complete "can include a single npm package" test

### ISSUE THREAD

**Issue by jkroso** [mixu/gluejs#6]
I'm on windows so can't run make. The command I used to run the tests is this:

`mocha -u exports -R spec test/glue.test.js`

It runs a few tests but gets stuck on the above mentioned test and never exits.

**Comment by mixu** [comment]
Thanks for reporting this. The issue was that gluejs wasn't tested on Windows. I needed to make a few changes into the path handling logic.

I've now added support for Windows - at least in the form that the tests pass. Though Windows support isn't a really huge priority for me personally, do let me know if you run into issues.

**Comment by jkroso** [comment]
Awesome thanks heaps

On Tue, Oct 30, 2012 at 6:00 PM, Mikito Takada notifications@github.comwrote:

> Thanks for reporting this. The issue was that gluejs wasn't tested on
> Windows. I needed to make a few changes into the path handling logic.
> 
> I've now added support for Windows - at least in the form that the tests
> pass. Though Windows support isn't a really huge priority for me
> personally, do let me know if you run into issues.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mixu/gluejs/issues/6#issuecomment-9895052.

## 

Regards, Jakeb

**Comment by jkroso** [comment]
FYI: It runs fine now and all the tests pass but the last test 'can include a package.json which causes all dependencies to be included' in package.test.js has missed something. While the packages dependencies are included the package itself is not included. i.e. `assert.ok(result[0]['./index.js'])` would fail. Also it doesn't look like their is any logic to handle npm packages made up of multiple files, but I could easily of missed something.  
EDIT: I had missed something, found it in the resolver package
